config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get "/delete", to: "main#deleteAll", as: 'deleteData'
  get "/upload", to: "main#upload", as: 'uploadData'
  resources :comics
  resources :magazines
  resources :mangakas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comic.rb
class Comic 
  include ActiveGraph::Node
  id_property :neo_id
  property :name, type: String
  property :image, type: String
  property :sinopsis, type: String
  property :generos, type: String
  property :is_active, type: Integer



end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :set_comic, only: %i[ show edit update destroy ]

  # GET /comics or /comics.json
  def index
    @comics = Comic.all
  end

  # GET /comics/1 or /comics/1.json
  def show
    @comic = Comic.find(params[:id])
  end

  # GET /comics/new
  def new
    @comic = Comic.new
  end

  # GET /comics/1/edit
  def edit
    @comic = Comic.find(params[:id])
  end

  # POST /comics or /comics.json
  def create
    @comic = Comic.new(comic_params)

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: "Comic was successfully created." }
        format.json { render :show, status: :created, location: @comic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comics/1 or /comics/1.json
  def update
    respond_to do |format|
      if @comic.update(comic_params)
        format.html { redirect_to @comic, notice: "Comic was successfully updated." }
        format.json { render :show, status: :ok, location: @comic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1 or /comics/1.json
  def destroy
    @comic = Comic.find(params[:id])
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url, notice: "Comic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic
      @comic = Comic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comic_params
      params.require(:comic).permit(:name, :image, :sinopsis, :generos, :is_active)
    end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_form.html.erb
<%= form_with(model: comic) do |form| %>
  <% if comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
        <% comic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label "Colocar URL de la imagen deseada" %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :sinopsis %>
    <%= form.text_field :sinopsis %>
  </div>

  <div class="field">
    <%= form.label :generos %>
    <%= form.text_field :generos %>
  </div>

  <div class="field">
    <%= form.label :is_active %>
    <%= form.number_field :is_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comics/edit.html.erb
<h1>Editing Comic</h1>

<%= render 'form', comic: @comic %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

app/views/comics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comics</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Sinopsis</th>
      <th>Generos</th>
      <th>Is active</th>
      <th colspan="3">Operations</th>
    </tr>
  </thead>

  <tbody>
    <% @comics.each do |comic| %>
      <tr>
        <td><%= comic.name %></td>
        <% if comic.image %>
          <td><img src="<%=comic.image%>" alt="A" width="100" height="100"/></td>
          <% else %>
          <td><img src="https://images.unsplash.com/photo-1580656449548-a2278870021d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=709&q=80" alt="Imagen"  width="100" height="100"/></td>
        <% end %>
        <td><%= comic.sinopsis %></td>
        <td><%= comic.generos %></td>
        <td>
        <% if comic.is_active == 0 %>
          Completo
        <% end %>

        <% if comic.is_active == 1 %>
          En emisión
        <% end %>

        <% if comic.is_active == 2 %>
          Pausado
        <% end %>

        <% if comic.is_active == 3 %>
          Abandonado
        <% end %>
        </td>
        <td><%= link_to 'Show', comic %></td>
        <td><%= link_to 'Edit', edit_comic_path(comic) %></td>
        <td><%= link_to 'Destroy', comic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comic', new_comic_path %> |
<%= link_to 'Menu', root_path %>

app/views/comics/new.html.erb
<h1>New Comic</h1>

<%= render 'form', comic: @comic %>

<%= link_to 'Back', comics_path %>

app/views/comics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comic.name %>
</p>

<p>
  <strong>Image:</strong>
  <% if @comic.image != nil %>
      <img src="<%=@comic.image%>" alt="A"/>
    <% else %>
      <img src="https://images.unsplash.com/photo-1580656449548-a2278870021d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=709&q=80" alt="Imagen" />
  <% end %>
</p>

<p>
  <strong>Sinopsis:</strong>
  <%= @comic.sinopsis %>
</p>

<p>
  <strong>Generos:</strong>
  <%= @comic.generos %>
</p>

<p>
  <strong>Estado</strong>
  <% if @comic.is_active == 0 %>
          Completo
        <% end %>
        
        <% if @comic.is_active == 1 %>
          En emisión
        <% end %>
        
        <% if @comic.is_active == 2 %>
          Pausado
        <% end %>

        <% if @comic.is_active == 3 %>
          Abandonado
        <% end %>
</p>

<%= link_to 'Edit', edit_comic_path(@comic) %> |
<%= link_to 'Back', comics_path %>