config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get "/delete", to: "main#deleteAll", as: 'deleteData'
  get "/upload", to: "main#upload", as: 'uploadData'
  resources :comics
  resources :magazines
  resources :mangakas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/mangaka.rb
class Mangaka 
  include ActiveGraph::Node
  id_property :neo_id
  property :name, type: String
  property :image, type: String



end

app/controllers/mangakas_controller.rb
class MangakasController < ApplicationController
  before_action :set_mangaka, only: %i[ show edit update destroy ]

  # GET /mangakas or /mangakas.json
  def index
    @mangakas = Mangaka.all
  end

  # GET /mangakas/1 or /mangakas/1.json
  def show
    @mangaka = Mangaka.find(params[:id])
  end

  # GET /mangakas/new
  def new
    @mangaka = Mangaka.new
  end

  # GET /mangakas/1/edit
  def edit
    @mangaka = Mangaka.find(params[:id])
  end

  # POST /mangakas or /mangakas.json
  def create
    @mangaka = Mangaka.new(mangaka_params)

    respond_to do |format|
      if @mangaka.save
        format.html { redirect_to @mangaka, notice: "Mangaka was successfully created." }
        format.json { render :show, status: :created, location: @mangaka }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mangaka.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mangakas/1 or /mangakas/1.json
  def update
    respond_to do |format|
      if @mangaka.update(mangaka_params)
        format.html { redirect_to @mangaka, notice: "Mangaka was successfully updated." }
        format.json { render :show, status: :ok, location: @mangaka }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mangaka.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mangakas/1 or /mangakas/1.json
  def destroy
    @mangaka.destroy
    respond_to do |format|
      format.html { redirect_to mangakas_url, notice: "Mangaka was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mangaka
      @mangaka = Mangaka.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mangaka_params
      params.require(:mangaka).permit(:name, :image)
    end
end

app/helpers/mangakas_helper.rb
module MangakasHelper
end

app/views/mangakas/_form.html.erb
<%= form_with(model: mangaka) do |form| %>
  <% if mangaka.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mangaka.errors.count, "error") %> prohibited this mangaka from being saved:</h2>

      <ul>
        <% mangaka.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mangakas/edit.html.erb
<h1>Editing Mangaka</h1>

<%= render 'form', mangaka: @mangaka %>

<%= link_to 'Show', @mangaka %> |
<%= link_to 'Back', mangakas_path %>

app/views/mangakas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mangakas</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3">Operations</th>
    </tr>
  </thead>

  <tbody>
    <% @mangakas.each do |mangaka| %>
      <tr>
        <td><%= mangaka.name %></td>
        
        <% if mangaka.image %>
          <td><img src="<%=mangaka.image%>" alt="A" width="100" height="100"/></td>
          <% else %>
          <td><img src="https://images.unsplash.com/photo-1580656449548-a2278870021d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=709&q=80" alt="Imagen"  width="100" height="100"/></td>
        <% end %>
        <td><%= link_to 'Show', mangaka %></td>
        <td><%= link_to 'Edit', edit_mangaka_path(mangaka) %></td>
        <td><%= link_to 'Destroy', mangaka, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mangaka', new_mangaka_path %> |
<%= link_to 'Menu', root_path %>

app/views/mangakas/new.html.erb
<h1>New Mangaka</h1>

<%= render 'form', mangaka: @mangaka %>

<%= link_to 'Back', mangakas_path %>

app/views/mangakas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mangaka.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @mangaka.image %>
</p>

<%= link_to 'Edit', edit_mangaka_path(@mangaka) %> |
<%= link_to 'Back', mangakas_path %>